In [1]:
import numpy as np

In [2]:
#define sigmoid activation function
def sigmoid(x):
    return 1/(1 + np.exp(-x))

In [3]:
#define sigmoid_prime function
def sigmoid_prime(x):
    return (sigmoid(x))*(1 - sigmoid(x))

In [4]:
#input data
data = np.array([[0, 0, 0, 0, 0], 
        [0, 0, 0, 1, 0], 
        [0, 0, 1, 0, 0],
        [0, 0, 1, 1, 0], 
        [0, 1, 0, 0, 0], 
        [0, 1, 0, 1, 0], 
        [0, 1, 1, 0, 0],
        [0, 1, 1, 1, 0], 
        [1, 0, 0, 0, 0], 
        [1, 0, 0, 1, 0], 
        [1, 0, 1, 0, 0],
        [1, 0, 1, 1, 0], 
        [1, 1, 0, 0, 0], 
        [1, 1, 0, 1, 0], 
        [1, 1, 1, 0, 0],
        [1, 1, 1, 1, 0],
        [0, 0, 0, 0, 1], 
        [0, 0, 0, 1, 1], 
        [0, 0, 1, 0, 1],
        [0, 0, 1, 1, 1], 
        [0, 1, 0, 0, 1], 
        [0, 1, 0, 1, 1], 
        [0, 1, 1, 0, 1],
        [0, 1, 1, 1, 1], 
        [1, 0, 0, 0, 1], 
        [1, 0, 0, 1, 1], 
        [1, 0, 1, 0, 1],
        [1, 0, 1, 1, 1], 
        [1, 1, 0, 0, 1], 
        [1, 1, 0, 1, 1], 
        [1, 1, 1, 0, 1],
        [1, 1, 1, 1, 1]])
print(data.shape)         

(32, 5)


In [5]:
#expected outputs
outputs = np.array([[0, 0],
                   [0, 1],
                   [1, 0],
                   [1, 1], 
                   [0, 1],
                   [0, 0],
                   [1, 1],
                   [1, 0],
                   [1, 0],
                   [1, 1],
                   [0, 0],
                   [0, 1],
                   [1, 1],
                   [1, 0],
                   [0, 1],
                   [0, 0],
                   [1, 1],
                   [1, 0],
                   [0, 1],
                   [0, 0],
                   [1, 0],
                   [1, 1],
                   [0, 0],
                   [0, 1],
                   [0, 1],
                   [0, 0],
                   [1, 1],
                   [1, 0],
                   [0, 0],
                   [0, 1],
                   [1, 0],
                   [1, 1]])
print(outputs.shape)

(32, 2)


In [8]:
#initialise weights for the neural network
weights_input_1 = np.random.rand(10, 5)
weights_1_output = np.random.rand(2, 10)

In [9]:
#define feedforward function
def feedforward(x):
    x0 = np.transpose([x])
    x1 = np.dot(weights_input_1, x0)
    h1 = sigmoid(x1)
    x2 = np.dot(weights_1_output, h1)
    output = sigmoid(x2)
    return output

In [10]:
feedforward(np.array([0, 0, 0, 0, 1]))

array([[0.97630794],
       [0.95713313]])

In [11]:
#define a function to update weights
def update_weights(x, y, learnrate):
    global weights_input_1
    global weights_1_output
    
    target = np.transpose([y])
    
    x0 = np.transpose([x])
    x1 = np.dot(weights_input_1, x0)
    h1 = sigmoid(x1)
    x2 = np.dot(weights_1_output, h1)
    output = sigmoid(x2)
    
    output_t = np.transpose(output)
    target_t = np.transpose(target)
    array = 0.5*((output_t - target_t)**2)
    running_error = np.sum(array)
    
    error = output - target
    
    delta = error*sigmoid_prime(x2)
    h1_t = np.transpose(h1)
    delta_weights_1_output = delta*h1_t
    
    w_1_o_t = np.transpose(weights_1_output)
    delta_1 = np.dot(w_1_o_t, delta)
    delta_2 = delta_1*sigmoid_prime(x1)
    x0_t = np.transpose(x0)
    delta_weights_input_1 = delta_2*x0_t
    
    weights_input_1 -= delta_weights_input_1*learnrate
    weights_1_output -= delta_weights_1_output*learnrate
    
    return running_error

In [12]:
update_weights([1, 2, 3, 4, 5], [1, 0], 0.1)

0.4959317175243802

In [13]:
print(weights_input_1)
print(weights_1_output)

[[0.02020381 0.87410759 0.76688599 0.48250396 0.16053887]
 [0.90382221 0.46859616 0.5269298  0.21629468 0.12446304]
 [0.81199041 0.59598899 0.00856733 0.99470955 0.77115809]
 [0.57949508 0.27364716 0.38756831 0.48481644 0.14055607]
 [0.06133628 0.95163934 0.82947136 0.71619851 0.00733034]
 [0.40872828 0.50909442 0.97132389 0.63043197 0.02078113]
 [0.12657296 0.84704074 0.51777679 0.46378778 0.36201686]
 [0.38984645 0.34092212 0.90995938 0.05220569 0.79131919]
 [0.24609562 0.86844136 0.97427808 0.66100482 0.1435584 ]
 [0.78012995 0.24625921 0.05318587 0.73790212 0.21425958]]
[[0.17810167 0.7364385  0.51781992 0.72106769 0.96232289 0.80314407
  0.88020674 0.84831912 0.55209108 0.36920329]
 [0.67109061 0.91190073 0.53227868 0.57575045 0.1948903  0.59822088
  0.24629571 0.4547333  0.39324666 0.9324308 ]]


In [15]:
#training loop
epochs = 10000
learnrate = 0.1
for e in range(epochs):
    error1 = 0
    for x, y in zip(data, outputs):
        running_error = update_weights(x, y, learnrate)
        error1 += running_error
    if e%1000 == 0:
        print("error :")
        print(error1*100)
        

error :
80.5689919676903
error :
15.297738832299492
error :
7.042070499736106
error :
4.1753292422805
error :
2.850811658594145
error :
2.1198077936119764
error :
1.6676926847668156
error :
1.3651557207409473
error :
1.1506657097211044
error :
0.9917295962332012


In [16]:
feedforward(np.array([1, 0, 0, 1, 0]))

array([[0.98321563],
       [0.99136338]])